name: README Info Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: Shineii86/Shineii86@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Asia/Kolkata"
          SHOW_DAILY_COMMIT: "True"
          SHOW_WEEKLY_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TOTAL_CONTRIBUTIONS: "True"
